Repository remyCases/MyDeputeFr, pull requests merged in 2025-04, with the labels that each got.

#2 [Minor] Clean Configurations
  cogs/deputeCommand.py
  config/__init__.py
  config/config.py
  download/download.py
  logger/logger.py
  main.py
  utils/deputeManager.py
  utils/scrutinManager.py
Labels: enhancement

#3 [Major] Rewrite downloads modules
  config/config.py
  download/download.py
  requirements-dev.txt
  tests/__init__.py
  tests/common.py
  tests/download/__init__.py
  tests/download/test_download.py
  tests/download/test_move_folder.py
  tests/download/test_unzip.py
  tests/download/test_update.py
Labels: enhancement

#9 [Minor] Add image and url for depute found for the nom and circo command
  cogs/deputeCommand.py
  utils/deputeManager.py
Labels: enhancement

#10 [Minor] Improve message result design for the scr command
  cogs/deputeCommand.py
Labels: enhancement

#14 [Minor] harmonazing command title
  cogs/deputeCommand.py
Labels: enhancement

#13 Update lock
  Makefile
  cogs/deputeCommand.py
  cogs/generalCommand.py
  config/config.py
  download/core.py
  download/download.py
  download/update.py
  main.py
  requirements-dev.txt
  tests/conftest.py
  tests/download/conftest.py
  tests/download/test_download.py
  tests/download/test_move_folder.py
  tests/download/test_unzip.py
  tests/download/test_update.py
  utils/__init__.py
  utils/botManager.py
  utils/cogManager.py
  utils/commandManager.py
  utils/utils.py
Labels: enhancement

#23 [Minor] Add some logging infos for processed message
  utils/botManager.py
Labels: enhancement

#24 Make Makefile cross plaform
  Makefile
Labels: enhancement

#26 Fix CI tests failing
  .github/workflows/coverage.yml
  config/config.py
  download/core.py
  handlers/deputeHandler.py
  tests/handlers/conftest.py
  utils/botManager.py
  utils/cogManager.py
  utils/commandManager.py
  utils/deputeManager.py
  utils/scrutinManager.py
Labels: bug

#18 Add Readme
  README.md
Labels: documentation

#27 Improve nom, vote, stats commands
  cogs/debugCommand.py
  cogs/deputeCommand.py
  handlers/debugHandler.py
  handlers/deputeHandler.py
  tests/handlers/test_circo_handler.py
  tests/handlers/test_dep_handler.py
  tests/handlers/test_nom_handler.py
  tests/handlers/test_scr_handler.py
  tests/handlers/test_stat_handler.py
  tests/handlers/test_vote_handler.py
  tests/utils/test_depute.py
  tests/utils/test_scrutin.py
  utils/deputeManager.py
  utils/scrutinManager.py
  utils/utils.py
Labels: bug, enhancement

#17 Adding end-user documentation
  cogs/deputeCommand.py
  docs/commandes.md
Labels: documentation
